export default {
  // Global page headers (https://go.nuxtjs.dev/config-head)
  head: {
    title: 'oxiox',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: '' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },

  // Global CSS (https://go.nuxtjs.dev/config-css)
  css: [
    'normalize.css/normalize.css',
    '~/assets/style.sass'
  ],

  // Plugins to run before rendering page (https://go.nuxtjs.dev/config-plugins)
  plugins: [
    { src: '@/plugins/vue-awesome-swiper', mode: 'client' },
    { src: '@/plugins/v-body-scroll-lock', mode: 'client' }
  ],

  // Auto import components (https://go.nuxtjs.dev/config-components)
  components: true,

  // Modules for dev and build (recommended) (https://go.nuxtjs.dev/config-modules)
  buildModules: [
    // https://go.nuxtjs.dev/eslint
    '@nuxtjs/eslint-module'
  ],

  // Modules (https://go.nuxtjs.dev/config-modules)
  modules: [
    ['nuxt-i18n', {
      strategy: 'prefix_except_default'
    }]
  ],
  i18n: {
    locales: [
      {
        code: 'en',
        name: 'en'
      },
      {
        code: 'ru',
        name: 'ru'
      }
    ],
    defaultLocale: 'en',
    warnHtmlInMessage: true,
    vueI18n: {
      messages: {
        fallbackLocale: 'en',
        en: {
          MainTitleOne: 'Create',
          MainTitleOneSpan: 'the best conditions',
          MaintitleOneMore: 'for your business with our software solutions',
          MainListOne: 'Web Development',
          MainListTwo: 'Mobile Apps Development',
          MainListThree: 'Custom Software Services',
          MainListFour: 'UI/UX Design',
          FreeOffer: 'Get a Free Offer',
          OurClients: 'Our Clients',
          MainTwoTitle: 'Web Development',
          MainTwoTextOne: 'Powerful, flexible, customizable, responsive, mobile-friendly, affordable, launch in record time.',
          MainTwoTextTwo: 'Our web development solutions handle all the above. Trusted for over four years, we are creating a new way to build a fantastic and reliable product that will produce tangible results for you and top-end solutions for your users.',
          MaintitleThree: 'Mobile Apps Development',
          MainThreeTextOne: 'As proven app developers, we empower end to end mobile solutions—both native and hybrid, regarding your goals, budget, and timelines.',
          MainThreeTextTwo: 'Our in-depth expertise in narrow niches allows us to see and use the opportunities others are missing. As a result, you get a unique mobile app that will take off—right at your fingertips.',
          MaintitleFour: 'Кастомное программное обеспечение',
          MainFourTextOne: 'We provide custom software services using emerging technologies. It means that we choose a variant that suits exactly your case.',
          MainFourTextTwo: 'Thus, you can focus on your business targets, succeed, and do not worry about any technical issues as we ensure your software concept full realization',
          MaintitleFive: 'UI/UX Design',
          MainFiveTextOne: 'Design is no longer about the wow factor. UI/UX Design is about providing personalization, simplicity, convenience, minimalism, engagement, and accessibility.',
          MainFiveTextTwo: 'We will create your brand identity with an eminently crafted visual strategy to maximize all opportunities of your business growing.',
          TechStack: 'Tech Stack',
          TellAbout: ' We know how to incorporate the tech solutions that best suit your case. Just drop us a line to get yours!',
          TellAboutSpan: 'Tell us about your project.',
          ContactUs: 'Contact Us',
          OurWorks: 'Our Works',
          OurWorksTitle: 'The Best App Ever',
          OurWorksText: 'The short but bright description of the best App ever',
          OurWorksButton: 'See Full Presentation',
          Testimonials: 'Testimonials',
          OurTeam: 'Our Team',
          OurTeamNameOne: 'Valera Grip',
          OurTeamNameTwo: 'Maria Shanny',
          OurTeamNameThree: 'Roman Boboyan',
          OurTeamProfOne: 'Chief Project Officer',
          OurTeamProfTwo: 'UX/UI Designer',
          OurTeamProfThree: 'Chief Technology Officer',
          GetAcquainted: 'Get Acquainted',
          Email: 'Drop Us a Line',
          Office: 'Our Office',
          OfficeAdressOne: 'Ukraine, Zaporizhzhia',
          OfficeAdressTwo: 'Soborny ave., 158',
          ContactTitle: 'Tell us about your project',
          Contact: 'Contacts',
          ContactName: '*Your Name',
          ContactEmail: '*E-mail',
          ContactPhone: '*Phone',
          ContactProject: 'Project details',
          ContactFile: 'Attach file',
          ContactFileSize: 'max filesizw 50Mb',
          ContactSend: 'Send',
          ContactSendText: 'By clicking on the button you agree with',
          ContactSendTextLink: 'Privacy Policy',
          ContactTitleSmall: 'Startup Investment Checklist',
          ContactText: 'Product pitch or product spec is not enough. You must prove that the value you bring is worth funding. And that’s how.',
          ContactCheck: 'Get a Checklist',
          FooterLinks: 'Links',
          FooterFollows: 'Follow Us',
          FooterLinkWorks: 'Our works',
          FooterLinkBlog: 'Blog',
          FooterLinkTechnologies: 'Technologies',
          FooterLinkContact: 'Contact Us',
          FooterLinkAbout: 'About Us',
          FooterLinkGet: 'Get a Checklist',
          FooterCopy: 'OXIOS © 2020 All Rights Reserved',
          ReviewNameOne: 'Marry Saley',
          ReviewTextOneOne: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          ReviewTextOneTwo: 'Eros sagittis elementum arcu pellentesque eget tristique. Faucibus sit risus a eu lacus nibh neque vitae.',
          ReviewNameTwo: 'Anna Osvald',
          ReviewTextTwoOne: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          ReviewTextTwoTwo: 'Eros sagittis elementum arcu pellentesque eget tristique. Faucibus sit risus a eu lacus nibh neque vitae.',
          ReviewNameThree: 'John Cena',
          ReviewTextThreeOne: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          ReviewTextThreeTwo: 'Eros sagittis elementum arcu pellentesque eget tristique. Faucibus sit risus a eu lacus nibh neque vitae.',
          HeaderLinkOne: 'Our Works',
          HeaderLinkTwo: 'Technologies',
          HeaderLinkThree: 'About Us',
          HeaderLinkThreeOne: 'Who We Are',
          HeaderLinkThreeTwo: 'Career',
          HeaderLinkThreeThree: 'Our Mission',
          HeaderLinkFour: 'Blog',
          HeaderButton: 'Hire Us',
          WorkTitle: 'Our Works',
          WorktitleOne: 'Developed the service for interior designers and architects «ProInterno»',
          WorktitleTwo: 'Developed multilanding for selling the jewelry caskets',
          WorktitleThree: 'Redesigned App of shop «Shanghai Pot»',
          WorkBtn: 'View the Presentation',
          ContactTextTitle: 'Do you wnat to discuss your project?',
          ContactTextButton: 'Contact Us',
          TechnologiesTitle: 'Technologies',
          TechnologiesText: 'We develop software that covers multiple platforms — web, Android/iOS, smart TV, wearables, IoT.',
          WeTitle: 'Who We Are',
          WeText: 'believes that overall success depends on each team member. We contribute to employees\' pro-growth. We are happy to share our knowledge with newcomers and are always ready to learn new approaches to solving new exciting and challenging tasks.',
          WeServices: 'Our Services',
          WeSubtitleOne: 'Mobile Apps Development',
          WeTextOne: 'As proven app developers, we empower end to end mobile solutions—both native and hybrid, regarding your goals, budget, and timelines',
          WeSubtitleTwo: 'Custom Software Services',
          WeTextTwo: 'We provide custom software services using emerging technologies. It means that we choose a variant that suits exactly your case',
          WeSubtitleThree: 'Web Development',
          WeTextThree: 'Powerful, flexible, customizable, responsive, mobile-friendly, affordable, launch in record time',
          WeSubtitleFour: 'UI/UX Design',
          WeTextFour: 'We will create your brand identity with an eminently crafted visual strategy to maximize all opportunities of your business growing',
          CareerTitleOne: 'Join The',
          CareerTitleTwo: 'Team',
          CareerTextOne: 'Today, OXIOS is a team that consists of quality code, effective management, creative marketing, and design. We design, test, create, and 100% responsible for the result.',
          CareerTextTwo: 'Our workflow combines exciting projects and ongoing pro-growth. We want to create the future today! We are not just looking for bright talents. We are looking for you to become a part of our team.',
          CareerWhy: 'Why Join',
          CareerItemOne: 'Pro-growth (webinars, lectures, conferences, courses, workshops)',
          CareerItemTwo: 'Competitive salary',
          CareerItemThree: 'Team building activities & corporate parties',
          CareerItemFour: 'Flexible schedule',
          CareerItemFive: 'Paid English classes',
          CareerItemSix: 'Paid gym membership',
          CareerItemSeven: 'Paid vacation (24 calendar days per year)',
          CareerItemNight: 'Paid sick days',
          CareerJob: 'Job Openings',
          MissionCitata: 'All that we do is guided by delivering solutions so that you can smoothly run your business everywhere, with no worries, without any barriers.',
          MissionTitleOne: 'Our Mission',
          MissionTextOneOne: 'As Bill Gates stated, ‘There will be two types of businesses in the next five years, those that are on the Internet, and those that are out of business.’',
          MissionTextOneTwo: 'We help improve and bring your business online through custom software solutions. The greatest achievement for us is to make maximum profit for your business, drive real value for your users, and ensure your product hits the top ratings.',
          MissionTextOneThree: 'We provide web and mobile tools and deliver advanced tech solutions to be implemented to guarantee high-quality, fast, seamless, flexible, and easy-to-use final product. Our mission is to create not just apps. We will help you implement solutions that everyone always is going to want.',
          MissionTitleTwo: 'Our Vision',
          MissionTextTwoOne: 'People now need not only highly effective products but fast and convenient as well.',
          MissionTextTwoTwo: 'With the rapid technologies expansion and intrusion of online solutions, the market has drastically changed. Offline spheres primarily constituting users’ everyday lives now suffer from devouring by mobile segment.',
          MissionTextTwoThree: 'Here end to end solutions arise, representing a new, increasingly developing field of innovative products.',
          MissionTextTwoFour: 'At OpenGeeksLab, we offer top-end solutions on the web and mobile development market, which will help your idea grow and conquer business hills by breathing new life into your customers’ daily routine.',
          MissionValue: 'Our Values',
          MissionValueTitleOne: 'OXIOS is about top-end service and results',
          MissionValueTextOne: 'We will develop your product so great that you do not want to make changes. We do not pursue quantity—we value high-end quality and results.',
          MissionValueTitleTwo: 'OXIOS is about trust',
          MissionValueTextTwo: 'Year after year, OpenGeeksLab has been recognized as one of Europe’s most talented developers. We have clientele across the globe that highly evaluates services we deliver and return to us to create new amazing products.',
          MissionValueTitleThree: 'OXIOS is about transparency',
          MissionValueTextThree: 'Due to transparency, we achieve the effect of your real presence in our workflow. We are working with two-week sprints accompanied by everyday meetups. After each sprint, we have a retrospective call and discuss the work segment—what was done well and what should be improved. As we are in the heart of Europe, we work during your working hours.',
          MissionValueTitleFour: 'OXIOS is about getting a step ahead',
          MissionValueTextFour: 'We are on a wave of emerging and changing trends to ensure a competitive advantage for your business that is not available to an average person. Therefore, you get the technical solutions that best suit your business model so that you can get a step ahead of competitors.',
          MissionValueTitleFive: 'OXIOS is about offering your customers a lifelike immersive experience',
          MissionValueTextFive: 'The modern market is wide-open to innovative digital solutions. We know how to transform your business to offer your customers a lifelike immersive experience and breathe new life into your customer’s daily routine.',
          MissionValueTitleSix: 'OXIOS is about moving beyond standard business models',
          MissionValueTextSix: 'We know how to use the software in the right way to move your business beyond standard models and revolutionize your opportunities. Choosing us, you help your organization grow and adapt to new dynamics, not just to fit in.',
          BlogTitle: 'Our Blog',
          BlogTitleItemOne: 'Checklist On App Analytics To Get Maximum Out Of Your Project',
          BlogTextItemOne: 'Intense intrusion of smartphones onto digital market resulted in quick brunch development. Things that ten years ago were inconceivable, now are commonly received...',
          BlogTitleItemTwo: 'Virtual Reality In Medicine: Top 13 Promising Use Cases',
          BlogTextItemTwo: 'Prospects and results of VR show that one can use this technology almost everywhere. It violates physics laws, overcomes boundaries between fiction and reality, whether it is traveling through space...',
          BlogTitleItemThree: 'How To Come Up With Travel App Idea: Top 16 Insights To Get Inspired',
          BlogTextItemThree: 'Tourism industry is continually reforming which leads to travel app phenomenon expansion. Modern travelers no longer want to waste lot of time planning trips, whether it is a vacation or a business case...',
          BlogTitleItemFour: '4 Tips On How To Choose A Tech Stack For Your Project',
          BlogTextItemFour: 'The project’s purpose determines what tech stack to apply. Not the other way around. Some features cannot be developed on a specific toolset. If you choose the technology stack without a strategic approach...',
          BlogTitleItemFive: 'How Your Company Can Solve Delivery Challenges',
          BlogTextItemFive: 'E-commerce trading more and more gets popular in modern circumstances triggering a fast growth of on-demand delivery services and making the last mile transportation niche boom...',
          BlogTitleItemSix: 'A Comprehensive Guide To Container Management Development',
          BlogTextItemSix: 'Shipping has long become an essential part of the modern e-commerce market, making efficient container management indispensable...',
          ShowMore: 'Show more',
          FilterOne: 'Latest',
          BlogItemTitle: 'Checklist On App Analytics To Get Maximum Out Of Your Project',
          BlogItemTextOne: 'Intense intrusion of smartphones onto digital market resulted in quick brunch development. Things that ten years ago were inconceivable, now are commonly received.',
          BlogItemTextTwo: 'Since its appearance mobile segment grew and expanded turning into one of the most profitable modern market spheres. Last year, it gained 461.7 billion dollars in revenue. This amount is forecasted to grow up to more than 935 billion dollars by 2023.',
          BlogItemTextThree: 'Mobile applications penetrate into our daily life making routines less tedious. According to statistics, Google Play and Apple App Store offer about 2 million various apps that are called to make customers’ life better. We have already discussed important criteria to rely on while choosing application type and singled out trends for mobile development, spotlighting most efficient mobile app KPIs.',
          BlogItemTextFoure: 'Still, just having an application is not enough for successful business running. To get maximum out of project you have to know how efficient it is. Thus, profound app analytics understanding stands for one more step towards your success.',
          BlogItemTextFive: 'In this post, OpenGeekLab will tell about key mobile app analytics metrics and disclose secrets on how different mobile app metrics tools actually work. Keep on reading!',
          BlogItemDescrTitle: 'App Analytics Metrics You Should Consider to Boost Your Product Success',
          BlogItemDescrTextTitle: 'Downloads',
          BlogItemDescrTextOne: 'Installs number stands among basic metrics to trace product’s success. It shows how many users actually downloaded the app from mobile store. These numbers are called to represent most general picture concerning analytics without further details. Downloads also influence app’s position in rating or search results.',
          BlogItemDescrTextTwo: 'However, downloads number is not synonymous to app active users. This metrics does not reflect whether the customer uses program or not. It might be installed due to peculiar promotion company and deleted right after downloading, or simply did not reach user satisfaction. On the basis of download analytics further metrics are counted.',
          Share: 'Share',
          ReactNativeTitle: 'Choose Our Vetted React Native App Developers To Work On Your Project',
          ReactNativeText: 'Our experts are in close cooperation and capable of delivering end to end software solutions that best suit your business model and result in success.',
          Examples: 'Examples',
          View: 'View'
        },
        ru: {
          MainTitleOne: 'Создайте',
          MainTitleOneSpan: 'лучшие условия',
          MaintitleOneMore: 'для вашего бизнеса с нашими программными решениями',
          MainListOne: 'Веб-разработка',
          MainListTwo: 'Разработка мобильных приложений',
          MainListThree: 'Заказное программное обеспечение',
          MainListFour: 'UI/UX дизайн',
          FreeOffer: 'Получите бесплатное предложение',
          OurClients: 'Наши клиенты',
          MainTwoTitle: 'Веб-разработка',
          MainTwoTextOne: 'Мощный, гибкий, настраиваемый, отзывчивый, удобный для мобильных устройств, доступный по цене, запуск в рекордные сроки.',
          MainTwoTextTwo: 'Наши решения для веб-разработки справляются со всем вышеперечисленным. Нам доверяют более четырех лет, и мы создаем новый способ создания фантастического и надежного продукта, который принесет ощутимые результаты для вас и лучшие решения для ваших пользователей.',
          MaintitleThree: 'Разработка мобильных приложений',
          MainThreeTextOne: 'Как проверенные разработчики приложений, мы предоставляем комплексные мобильные решения - как нативные, так и гибридные, в зависимости от ваших целей, бюджета и сроков.',
          MainThreeTextTwo: 'Наш глубокий опыт работы в узких нишах позволяет нам видеть и использовать возможности, которых не хватает другим. В результате вы получите уникальное мобильное приложение, которое станет популярным - у вас под рукой.',
          MaintitleFour: 'Разработка мобильных приложений',
          MainFourTextOne: 'Мы предоставляем индивидуальные программные услуги с использованием новейших технологий. Значит, мы подбираем вариант, который подходит именно вам.',
          MainFourTextTwo: 'Таким образом, вы можете сосредоточиться на своих бизнес-целях, добиться успеха и не беспокоиться о технических проблемах, поскольку мы гарантируем полную реализацию вашей концепции программного обеспечения.',
          MaintitleFive: 'UI/UX дизайн',
          MainFiveTextOne: 'Дизайн не больших о вау-эффектов. UI/UX Design - это персонализация, простота, удобство, минимализм, вовлеченность и доступность.',
          MainFiveTextTwo: 'Мы создадим идентичность вашего бренда с помощью тщательно продуманной визуальной стратегии, чтобы максимально использовать все возможности роста вашего бизнеса.',
          TechStack: 'Стек технологий',
          TellAbout: 'Мы знаем, как включить технические решения, которые лучше всего подходят для вашего случая. Просто напишите нам, чтобы получить свое!',
          TellAboutSpan: 'Расскажите о своем проекте.',
          ContactUs: 'Связаться с нами',
          OurWorks: 'Наши работы',
          OurWorksTitle: 'Лучшее приложение на свете',
          OurWorksText: 'Краткое, но яркое описание лучшего приложения на свете',
          OurWorksButton: 'Посмотреть полную презентацию',
          Testimonials: 'Отзывы',
          OurTeam: 'Наша команда',
          OurTeamNameOne: 'Валерий Грип',
          OurTeamNameTwo: 'Мария Шенни',
          OurTeamNameThree: 'Роман Бобоян',
          OurTeamProfOne: 'Главный проектный директор',
          OurTeamProfTwo: 'UX/UI Дизайнер',
          OurTeamProfThree: 'Главный технический директор',
          GetAcquainted: 'Познакомиться',
          Email: 'Напишите нам',
          Office: 'Наш офис',
          OfficeAdressOne: 'Украина, Запорожье',
          OfficeAdressTwo: 'Соборный проспект, 158',
          ContactTitle: 'Расскажите о своем проекте',
          Contact: 'Контакты',
          ContactName: '*Ваше имя',
          ContactEmail: '*E-mail',
          ContactPhone: '*Телефон',
          ContactProject: 'Детали проекта',
          ContactFile: 'Прикрепить файл',
          ContactFileSize: 'максимальный размер файла 50Mb',
          ContactSend: 'Отправить',
          ContactSendText: 'Нажимая на кнопку, вы соглашаетесь с ',
          ContactSendTextLink: 'Политикой конфиденциальности',
          ContactTitleSmall: 'Чеклист инвестиций в стартап',
          ContactText: 'Недостаточно шага или спецификации продукта. Мы должны доказать, что приносимая вами ценность стоит финансирования. А вот как.',
          ContactCheck: 'Получите контрольный список',
          FooterLinks: 'Ссылки',
          FooterFollows: 'Подписывайтесь на нас',
          FooterLinkWorks: 'Наши работы',
          FooterLinkBlog: 'Блог',
          FooterLinkTechnologies: 'Технологии',
          FooterLinkContact: 'Связаться с нами',
          FooterLinkAbout: 'О нас',
          FooterLinkGet: 'Получите чеклист',
          FooterCopy: 'OXIOS © 2020 Все права защищены',
          ReviewNameOne: 'Marry Saley',
          ReviewTextOneOne: 'Таким образом начало повседневной работы по формированию позиции влечет за собой процесс внедрения.',
          ReviewTextOneTwo: 'и модернизации форм развития. Равным образом постоянный количественный рост.',
          ReviewNameTwo: 'Anna Osvald',
          ReviewTextTwoOne: 'Таким образом начало повседневной работы по формированию позиции влечет за собой процесс внедрения.',
          ReviewTextTwoTwo: 'и модернизации форм развития. Равным образом постоянный количественный рост.',
          ReviewNameThree: 'John Cena',
          ReviewTextThreeOne: 'Таким образом начало повседневной работы по формированию позиции влечет за собой процесс внедрения.',
          ReviewTextThreeTwo: 'и модернизации форм развития. Равным образом постоянный количественный рост.',
          HeaderLinkOne: 'Наши работы',
          HeaderLinkTwo: 'Технологии',
          HeaderLinkThree: 'О нас',
          HeaderLinkThreeOne: 'Кто мы есть',
          HeaderLinkThreeTwo: 'Карьера',
          HeaderLinkThreeThree: 'Наша миссия',
          HeaderLinkFour: 'Блог',
          HeaderButton: 'Нанять нас',
          WorkTitle: 'Наши работы',
          WorktitleOne: 'Разработан сервис для дизайнеров интерьеров и архитекторов «ProInterno».',
          WorktitleTwo: 'Разработан мультивендинг по продаже шкатулок.',
          WorktitleThree: 'Обновленное приложение магазина «Shanghai Pot»',
          WorkBtn: 'Посмотреть презентацию',
          ContactTextTitle: 'Вы хотите обсудить проект?',
          ContactTextButton: 'Связаться с нами',
          TechnologiesTitle: 'Технологии',
          TechnologiesText: 'Мы разрабатываем программное обеспечение для нескольких платформ - Интернет, Android / iOS, Smart TV, интернет вещей.',
          WeTitle: 'Кто мы есть',
          WeText: 'считает, что общий успех зависит от каждого члена команды. Мы вносим вклад в развитие сотрудников. Мы рады поделиться своими знаниями с новичками и всегда готовы изучать новые подходы к решению новых интересных и сложных задач.',
          WeServices: 'Наши сервисы',
          WeSubtitleOne: 'Разработка мобильных приложений',
          WeTextOne: 'Как проверенные разработчики приложений, мы предоставляем комплексные мобильные решения - как собственные, так и гибридные, в зависимости от ваших целей, бюджета и сроков.',
          WeSubtitleTwo: 'Заказное программное обеспечение',
          WeTextTwo: 'Мы предоставляем индивидуальные программные услуги с использованием новейших технологий. Это значит, что мы подбираем вариант, который подходит именно вашему случаю.',
          WeSubtitleThree: 'Веб-разработка',
          WeTextThree: 'Мощный, гибкий, настраиваемый, отзывчивый, удобный для мобильных устройств, доступный по цене, запуск в рекордные сроки',
          WeSubtitleFour: 'UI/UX Дизайн',
          WeTextFour: 'Мы создадим идентичность вашего бренда с помощью тщательно продуманной визуальной стратегии, чтобы максимально использовать все возможности роста вашего бизнеса.',
          CareerTitleOne: 'Присоединяйся к',
          CareerTitleTwo: 'Команда',
          CareerTextOne: 'Сегодня OXIOS - это команда, состоящая из качественного кода, эффективного управления, креативного маркетинга и дизайна. Мы проектируем, тестируем, создаем и на 100% отвечаем за результат.',
          CareerTextTwo: 'Наш рабочий процесс сочетает в себе интересные проекты и постоянный рост. Мы хотим творить будущее уже сегодня! Мы не просто ищем яркие таланты. Мы ждем, чтобы вы стали частью нашей команды.',
          CareerWhy: 'Зачем присоединяться',
          CareerItemOne: 'Pro-growth (вебинары, лекции, конференции, курсы, мастер-классы)',
          CareerItemTwo: 'Конкурентоспособная заработная плата',
          CareerItemThree: 'Тимбилдинг и корпоративные вечеринки',
          CareerItemFour: 'Гибкий график',
          CareerItemFive: 'Платные уроки английского',
          CareerItemSix: 'Платный абонемент в спортзал',
          CareerItemSeven: 'Оплачиваемый отпуск (24 календарных дня в году)',
          CareerItemNight: 'Оплачиваемые больничные дни',
          CareerJob: 'Вакансии',
          MissionCitata: 'Все, что мы делаем, основывается на предоставлении решений, чтобы вы могли беспрепятственно вести свой бизнес везде, без забот и без каких-либо препятствий.',
          MissionTitleOne: 'Наша миссия',
          MissionTextOneOne: 'Как заявил Билл Гейтс, «в следующие пять лет будет два типа предприятий: те, которые работают в Интернете, и те, которые не работают».',
          MissionTextOneTwo: 'Мы помогаем улучшить и вывести ваш бизнес в онлайн с помощью индивидуальных программных решений. Самым большим достижением для нас является получение максимальной прибыли для вашего бизнеса, повышение реальной ценности для ваших пользователей и обеспечение того, чтобы ваш продукт попал в высшие рейтинги.',
          MissionTextOneThree: 'Мы предоставляем веб-инструменты и мобильные инструменты, а также передовые технические решения, которые должны быть внедрены, чтобы гарантировать высокое качество, скорость, бесперебойность, гибкость и простоту использования конечного продукта. Наша миссия - создавать не просто приложения. Мы поможем вам реализовать решения, которые всегда будут нужны каждому.',
          MissionTitleTwo: 'Наше виденье',
          MissionTextTwoOne: 'Людям нужны не только высокоэффективные продукты, но и быстрые и удобные.',
          MissionTextTwoTwo: 'С быстрым развитием технологий и появлением онлайн-решений рынок резко изменился. Офлайн-сферы, составляющие в первую очередь повседневную жизнь пользователей, теперь страдают от поглощения мобильным сегментом.',
          MissionTextTwoThree: 'Здесь возникают сквозные решения, представляющие новую, все более и более развивающуюся область инновационных продуктов.',
          MissionTextTwoFour: 'В OpenGeeksLab мы предлагаем топовые решения на рынке веб- и мобильной разработки, которые помогут вашей идее развиваться и покорять холмы бизнеса, вдохнув новую жизнь в повседневную жизнь ваших клиентов.',
          MissionValue: 'Наши ценности',
          MissionValueTitleOne: 'OXIOS - это первоклассный сервис и результат',
          MissionValueTextOne: 'Мы разработаем ваш продукт настолько хорошо, что вы не захотите вносить изменения. Мы не гонимся за количеством - мы ценим высокое качество и результат.',
          MissionValueTitleTwo: 'OXIOS - это доверие',
          MissionValueTextTwo: 'Год за годом OpenGeeksLab признавался одним из самых талантливых разработчиков в Европе. У нас есть клиентура по всему миру, которая высоко оценивает услуги, которые мы предоставляем, и возвращаемся к нам, чтобы создавать новые удивительные продукты.',
          MissionValueTitleThree: 'OXIOS - это прозрачность',
          MissionValueTextThree: 'Благодаря прозрачности мы добиваемся эффекта вашего реального присутствия в нашем рабочем процессе. Мы работаем с двухнедельными спринтами, которые сопровождаются ежедневными встречами. После каждого спринта мы проводим ретроспективный звонок и обсуждаем сегмент работы - что было сделано хорошо, а что нужно улучшить. Поскольку мы находимся в самом сердце Европы, мы работаем в ваше рабочее время.',
          MissionValueTitleFour: 'OXIOS - это шаг вперед',
          MissionValueTextFour: 'Мы находимся на волне новых и меняющихся тенденций, чтобы обеспечить конкурентное преимущество для вашего бизнеса, недоступное обычному человеку. Таким образом, вы получаете технические решения, которые лучше всего подходят для вашей бизнес-модели, чтобы быть на шаг впереди конкурентов.',
          MissionValueTitleFive: 'OXIOS предлагает вашим клиентам реалистичное погружение',
          MissionValueTextFive: 'Современный рынок широко открыт для инновационных цифровых решений. Мы знаем, как преобразовать ваш бизнес, чтобы предложить вашим клиентам реалистичный опыт погружения и вдохнуть новую жизнь в повседневную жизнь ваших клиентов.',
          MissionValueTitleSix: 'OXIOS - это выход за рамки стандартных бизнес-моделей',
          MissionValueTextSix: 'Мы знаем, как правильно использовать программное обеспечение, чтобы вывести ваш бизнес за рамки стандартных моделей и революционизировать ваши возможности. Выбирая нас, вы помогаете своей организации расти и адаптироваться к новой динамике, а не просто вписываться в нее.',
          BlogTitle: 'Наш блог',
          BlogTitleItemOne: 'Контрольный список по аналитике приложений, чтобы получить максимальную отдачу от вашего проекта',
          BlogTextItemOne: 'Интенсивное проникновение смартфонов на цифровой рынок привело к быстрому развитию отрасли. То, что десять лет назад было немыслимо, теперь принято...',
          BlogTitleItemTwo: 'Виртуальная реальность в медицине: 13 самых перспективных сценариев использования',
          BlogTextItemTwo: 'Перспективы и результаты VR показывают, что эту технологию можно использовать практически везде. Он нарушает законы физики, преодолевает границы между вымыслом и реальностью, независимо от того, путешествует ли он в космосе...',
          BlogTitleItemThree: 'Как придумать идею приложения для путешествий: 16 главных идей для вдохновения',
          BlogTextItemThree: 'Индустрия туризма постоянно реформируется, что приводит к расширению феномена туристических приложений. Современные путешественники больше не хотят тратить много времени на планирование поездок, будь то отпуск или бизнес ...',
          BlogTitleItemFour: '4 совета о том, как выбрать технический стек для вашего проекта',
          BlogTextItemFour: 'Цель проекта определяет, какой технологический стек применять. А не наоборот. Некоторые функции невозможно разработать с использованием определенного набора инструментов. Если вы выберете стек технологий без стратегического подхода ...',
          BlogTitleItemFive: 'Как ваша компания может решать проблемы доставки',
          BlogTextItemFive: 'Электронная коммерция становится все более популярной в современных условиях, вызывая быстрый рост услуг по доставке по запросу и делая транспортную нишу последней мили бумом...',
          BlogTitleItemSix: 'Комплексное руководство по развитию управления контейнерами',
          BlogTextItemSix: 'Морские перевозки давно стали неотъемлемой частью современного рынка электронной коммерции, что делает эффективное управление контейнерами незаменимым ...',
          ShowMore: 'Показать больше',
          FilterOne: 'Последние',
          BlogItemTitle: 'Контрольный список по аналитике приложений, чтобы получить максимальную отдачу от вашего проекта',
          BlogItemTextOne: 'Интенсивное проникновение смартфонов на цифровой рынок привело к быстрому развитию отрасли. То, что десять лет назад было немыслимо, теперь принято.',
          BlogItemTextTwo: 'С момента своего появления мобильный сегмент рос и расширялся, превратившись в одну из самых прибыльных современных рыночных сфер. В прошлом году выручка компании составила 461,7 миллиарда долларов. По прогнозам, к 2023 году эта сумма вырастет до более 935 миллиардов долларов.',
          BlogItemTextThree: 'Мобильные приложения проникают в нашу повседневную жизнь, делая рутины менее утомительными. По статистике, Google Play и Apple App Store предлагают около 2 миллионов различных приложений, призванных сделать жизнь клиентов лучше. Мы уже обсудили важные критерии, на которые следует опираться при выборе типа приложения, и выделили тенденции мобильной разработки, выделив наиболее эффективные KPI мобильных приложений.',
          BlogItemTextFoure: 'Тем не менее, для успешного ведения бизнеса недостаточно просто иметь приложение. Чтобы получить от проекта максимум, нужно знать, насколько он эффективен. Таким образом, глубокое понимание аналитики приложений - это еще один шаг к вашему успеху.',
          BlogItemTextFive: 'В этом посте OpenGeekLab расскажет о ключевых метриках аналитики мобильных приложений и раскроет секреты того, как на самом деле работают различные инструменты метрик мобильных приложений. Продолжайте читать!',
          BlogItemDescrTitle: 'Метрики аналитики приложений, которые следует учитывать, чтобы повысить успех вашего продукта',
          BlogItemDescrTextTitle: 'Скачивание',
          BlogItemDescrTextOne: 'Число установок является одним из основных показателей для отслеживания успеха продукта. Он показывает, сколько пользователей фактически загрузили приложение из мобильного магазина. Эти числа призваны представить наиболее общую картину, касающуюся аналитики, без дополнительных деталей. Загрузки также влияют на позицию приложения в рейтинге или в результатах поиска.',
          BlogItemDescrTextTwo: 'Однако количество загрузок не является синонимом активных пользователей приложения. Эти показатели не отражают, использует ли клиент программу или нет. Он мог быть установлен из-за особой рекламной компании и удален сразу после загрузки, или просто не удовлетворил пользователя. На основе аналитики загрузок подсчитываются дальнейшие показатели.',
          Share: 'Поделиться',
          ReactNativeTitle: 'Выберите наших проверенных разработчиков приложений React Native для работы над вашим проектом',
          ReactNativeText: 'Наши специалисты работают в тесном сотрудничестве и могут предоставить комплексные программные решения, которые наилучшим образом соответствуют вашей бизнес-модели и приводят к успеху.',
          Examples: 'Примеры',
          View: 'Посмотреть'
        }
      }
    }

  },

  // Build Configuration (https://go.nuxtjs.dev/config-build)
  build: {
  }
}
